;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-or-skip-quote
	indent-for-tab-command
	kill-region
	org-self-insert-command
	scroll-down-line
	skeleton-pair-insert-maybe
	smex
	))

(setq mc/cmds-to-run-once
      '(
	autopair-insert-opening
	autopair-skip-close-maybe
	beginning-of-buffer
	end-of-buffer
	mouse-save-then-kill
	org-force-self-insert
	))
