;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-or-skip-quote
	org-self-insert-command
	skeleton-pair-insert-maybe
	))

(setq mc/cmds-to-run-once
      '(
	autopair-insert-opening
	autopair-skip-close-maybe
	mouse-save-then-kill
	org-force-self-insert
	))
